//! Compact, fully local sentence embeddings used by question search.
//!
//! The quantized MiniLM model is compiled into the native backend. Document
//! vectors are generated by the Rust `semantic-index` binary and quantized to
//! signed bytes; query vectors are produced at runtime by the same model.

use std::collections::HashMap;

use fastembed::{
    InitOptionsUserDefined, Pooling, TextEmbedding, TokenizerFiles, UserDefinedEmbeddingModel,
};

use crate::taxonomy::MAX_SUBTAGS;

const MODEL_BYTES: &[u8] = include_bytes!("../models/semantic/model_quantized.onnx");
const TOKENIZER_BYTES: &[u8] = include_bytes!("../models/semantic/tokenizer.json");
const CONFIG_BYTES: &[u8] = include_bytes!("../models/semantic/config.json");
const SPECIAL_TOKENS_BYTES: &[u8] = include_bytes!("../models/semantic/special_tokens_map.json");
const TOKENIZER_CONFIG_BYTES: &[u8] = include_bytes!("../models/semantic/tokenizer_config.json");

const INDEX_MAGIC: &[u8; 8] = b"PLOOPSE1";
pub const INDEX_FORMAT_VERSION: u16 = 3;
const WORDS_PER_CHUNK: usize = 110;
const CHUNK_OVERLAP: usize = 16;
const MAX_CHUNKS_PER_QUESTION: usize = 8;

pub const EMBEDDING_DIMENSIONS: usize = 384;
pub const MODEL_NAME: &str = "Xenova/paraphrase-MiniLM-L3-v2 (q8)";

pub struct SemanticEncoder {
    model: TextEmbedding,
}

impl SemanticEncoder {
    pub fn new(intra_threads: usize) -> Result<Self, String> {
        let tokenizer_files = TokenizerFiles {
            tokenizer_file: TOKENIZER_BYTES.to_vec(),
            config_file: CONFIG_BYTES.to_vec(),
            special_tokens_map_file: SPECIAL_TOKENS_BYTES.to_vec(),
            tokenizer_config_file: TOKENIZER_CONFIG_BYTES.to_vec(),
        };
        let model = UserDefinedEmbeddingModel::new(MODEL_BYTES.to_vec(), tokenizer_files)
            .with_pooling(Pooling::Mean);
        let options = InitOptionsUserDefined::new()
            .with_max_length(512)
            .with_intra_threads(intra_threads.max(1));
        let model = TextEmbedding::try_new_from_user_defined(model, options)
            .map_err(|error| format!("Failed to initialise semantic model: {error}"))?;
        Ok(Self { model })
    }

    pub fn embed(
        &mut self,
        texts: Vec<String>,
        batch_size: usize,
    ) -> Result<Vec<Vec<f32>>, String> {
        if texts.is_empty() {
            return Ok(Vec::new());
        }
        let embeddings = self
            .model
            .embed(texts, Some(batch_size.max(1)))
            .map_err(|error| format!("Failed to create semantic embedding: {error}"))?;
        if embeddings
            .iter()
            .any(|embedding| embedding.len() != EMBEDDING_DIMENSIONS)
        {
            return Err("Semantic model returned an unexpected vector size".to_string());
        }
        Ok(embeddings)
    }

    pub fn embed_query(&mut self, query: &str) -> Result<Vec<f32>, String> {
        self.embed(vec![query.to_string()], 1)?
            .into_iter()
            .next()
            .ok_or_else(|| "Semantic model returned no query vector".to_string())
    }
}

pub fn canonical_question_text(question: &str, options: &[(&str, &str)]) -> String {
    let prompt = question.trim();
    let options = options
        .iter()
        .map(|(id, text)| format!("({}) {}", id, text.trim()))
        .collect::<Vec<_>>()
        .join(" ");
    if options.is_empty() {
        prompt.to_string()
    } else {
        format!("{prompt}\n{options}")
    }
}

pub fn chunk_text(text: &str) -> Vec<String> {
    let words = text.split_whitespace().collect::<Vec<_>>();
    if words.len() <= WORDS_PER_CHUNK {
        return vec![words.join(" ")];
    }

    let mut chunks = Vec::new();
    let step = WORDS_PER_CHUNK - CHUNK_OVERLAP;
    let mut start = 0;
    while start < words.len() && chunks.len() < MAX_CHUNKS_PER_QUESTION {
        let end = (start + WORDS_PER_CHUNK).min(words.len());
        chunks.push(words[start..end].join(" "));
        if end == words.len() {
            break;
        }
        start += step;
    }
    chunks
}

pub fn fingerprint(text: &str) -> u64 {
    let mut hash = 0xcbf29ce484222325_u64;
    for byte in text.as_bytes() {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(0x100000001b3);
    }
    hash
}

#[derive(Debug, Clone)]
pub struct QuantizedVector {
    inverse_norm: f32,
    values: Box<[i8]>,
}

impl QuantizedVector {
    pub fn from_embedding(embedding: &[f32]) -> Result<Self, String> {
        if embedding.len() != EMBEDDING_DIMENSIONS {
            return Err(format!(
                "Expected {EMBEDDING_DIMENSIONS} embedding values, found {}",
                embedding.len()
            ));
        }
        let max_absolute = embedding
            .iter()
            .map(|value| value.abs())
            .fold(0.0_f32, f32::max);
        let multiplier = if max_absolute > 0.0 {
            127.0 / max_absolute
        } else {
            1.0
        };
        let mut squared_norm = 0.0_f32;
        let values = embedding
            .iter()
            .map(|value| {
                let quantized = (value * multiplier).round().clamp(-127.0, 127.0) as i8;
                squared_norm += f32::from(quantized).powi(2);
                quantized
            })
            .collect::<Vec<_>>()
            .into_boxed_slice();
        let inverse_norm = if squared_norm > 0.0 {
            squared_norm.sqrt().recip()
        } else {
            0.0
        };
        Ok(Self {
            inverse_norm,
            values,
        })
    }

    fn similarity(&self, query: &[f32]) -> f32 {
        self.values
            .iter()
            .zip(query)
            .map(|(left, right)| f32::from(*left) * right)
            .sum::<f32>()
            * self.inverse_norm
    }
}

#[derive(Debug, Clone)]
pub struct SemanticRecord {
    pub id: String,
    pub fingerprint: u64,
    pub main_tag: String,
    pub subtags: Vec<String>,
    pub content_vectors: Vec<QuantizedVector>,
    pub taxonomy_vector: QuantizedVector,
}

#[derive(Debug, Clone, Copy)]
pub struct SemanticSimilarities {
    pub content: f32,
    pub taxonomy: f32,
}

#[derive(Debug, Clone)]
pub struct SemanticIndex {
    dimensions: usize,
    records: HashMap<String, SemanticRecord>,
}

impl SemanticIndex {
    pub fn from_records(records: Vec<SemanticRecord>) -> Self {
        Self {
            dimensions: EMBEDDING_DIMENSIONS,
            records: records
                .into_iter()
                .map(|record| (record.id.clone(), record))
                .collect(),
        }
    }

    pub fn from_bytes(bytes: &[u8]) -> Result<Self, String> {
        let mut reader = IndexReader::new(bytes);
        if reader.take(8)? != INDEX_MAGIC {
            return Err("Semantic index has an invalid header".to_string());
        }
        let version = reader.read_u16()?;
        if version != INDEX_FORMAT_VERSION {
            return Err(format!("Unsupported semantic index version: {version}"));
        }
        let dimensions = usize::from(reader.read_u16()?);
        if dimensions != EMBEDDING_DIMENSIONS {
            return Err(format!("Unsupported semantic vector size: {dimensions}"));
        }
        let record_count = reader.read_u32()? as usize;
        let mut records = HashMap::with_capacity(record_count);

        for _ in 0..record_count {
            let id_length = usize::from(reader.read_u16()?);
            let fingerprint = reader.read_u64()?;
            let content_vector_count = usize::from(reader.read_u16()?);
            if content_vector_count == 0 {
                return Err("Semantic index record has no content vectors".to_string());
            }
            let main_tag_length = usize::from(reader.read_u16()?);
            let subtag_count = usize::from(reader.read_u16()?);
            if subtag_count > MAX_SUBTAGS {
                return Err(format!(
                    "Semantic index record has {subtag_count} subtags; maximum is {MAX_SUBTAGS}"
                ));
            }
            let id = std::str::from_utf8(reader.take(id_length)?)
                .map_err(|_| "Semantic index contains an invalid question id".to_string())?
                .to_string();
            let main_tag = std::str::from_utf8(reader.take(main_tag_length)?)
                .map_err(|_| "Semantic index contains an invalid main tag".to_string())?
                .to_string();
            if main_tag.trim().is_empty() {
                return Err(format!("Semantic index record has no main tag: {id}"));
            }
            let mut subtags = Vec::with_capacity(subtag_count);
            for _ in 0..subtag_count {
                let subtag_length = usize::from(reader.read_u16()?);
                let subtag = std::str::from_utf8(reader.take(subtag_length)?)
                    .map_err(|_| "Semantic index contains an invalid subtag".to_string())?
                    .to_string();
                if subtag.trim().is_empty() {
                    return Err(format!("Semantic index record has an empty subtag: {id}"));
                }
                subtags.push(subtag);
            }
            let mut content_vectors = Vec::with_capacity(content_vector_count);
            for _ in 0..content_vector_count {
                let inverse_norm = reader.read_f32()?;
                let values = reader
                    .take(dimensions)?
                    .iter()
                    .map(|value| *value as i8)
                    .collect::<Vec<_>>()
                    .into_boxed_slice();
                content_vectors.push(QuantizedVector {
                    inverse_norm,
                    values,
                });
            }
            let taxonomy_inverse_norm = reader.read_f32()?;
            let taxonomy_values = reader
                .take(dimensions)?
                .iter()
                .map(|value| *value as i8)
                .collect::<Vec<_>>()
                .into_boxed_slice();
            records.insert(
                id.clone(),
                SemanticRecord {
                    id,
                    fingerprint,
                    main_tag,
                    subtags,
                    content_vectors,
                    taxonomy_vector: QuantizedVector {
                        inverse_norm: taxonomy_inverse_norm,
                        values: taxonomy_values,
                    },
                },
            );
        }

        if !reader.is_finished() {
            return Err("Semantic index contains trailing data".to_string());
        }
        Ok(Self {
            dimensions,
            records,
        })
    }

    pub fn to_bytes(&self) -> Result<Vec<u8>, String> {
        let mut output = Vec::new();
        output.extend_from_slice(INDEX_MAGIC);
        output.extend_from_slice(&INDEX_FORMAT_VERSION.to_le_bytes());
        output.extend_from_slice(&(self.dimensions as u16).to_le_bytes());
        output.extend_from_slice(&(self.records.len() as u32).to_le_bytes());
        let mut records = self.records.values().collect::<Vec<_>>();
        records.sort_by(|left, right| left.id.cmp(&right.id));

        for record in records {
            if record.main_tag.trim().is_empty() {
                return Err(format!("Question has no main tag: {}", record.id));
            }
            if record.subtags.len() > MAX_SUBTAGS {
                return Err(format!(
                    "Question {} has {} subtags; maximum is {MAX_SUBTAGS}",
                    record.id,
                    record.subtags.len()
                ));
            }
            let id = record.id.as_bytes();
            let id_length = u16::try_from(id.len())
                .map_err(|_| format!("Question id is too long: {}", record.id))?;
            if record.content_vectors.is_empty() {
                return Err(format!("Question has no semantic content: {}", record.id));
            }
            let content_vector_count = u16::try_from(record.content_vectors.len())
                .map_err(|_| format!("Too many semantic chunks: {}", record.id))?;
            let main_tag = record.main_tag.as_bytes();
            let main_tag_length = u16::try_from(main_tag.len())
                .map_err(|_| format!("Main tag is too long: {}", record.main_tag))?;
            let subtag_count = u16::try_from(record.subtags.len())
                .map_err(|_| format!("Too many subtags: {}", record.id))?;
            output.extend_from_slice(&id_length.to_le_bytes());
            output.extend_from_slice(&record.fingerprint.to_le_bytes());
            output.extend_from_slice(&content_vector_count.to_le_bytes());
            output.extend_from_slice(&main_tag_length.to_le_bytes());
            output.extend_from_slice(&subtag_count.to_le_bytes());
            output.extend_from_slice(id);
            output.extend_from_slice(main_tag);
            for subtag in &record.subtags {
                let bytes = subtag.as_bytes();
                let length = u16::try_from(bytes.len())
                    .map_err(|_| format!("Subtag is too long: {subtag}"))?;
                output.extend_from_slice(&length.to_le_bytes());
                output.extend_from_slice(bytes);
            }
            for vector in &record.content_vectors {
                output.extend_from_slice(&vector.inverse_norm.to_le_bytes());
                output.extend(vector.values.iter().map(|value| *value as u8));
            }
            output.extend_from_slice(&record.taxonomy_vector.inverse_norm.to_le_bytes());
            output.extend(
                record
                    .taxonomy_vector
                    .values
                    .iter()
                    .map(|value| *value as u8),
            );
        }
        Ok(output)
    }

    pub fn len(&self) -> usize {
        self.records.len()
    }

    pub fn is_empty(&self) -> bool {
        self.records.is_empty()
    }

    pub fn contains(&self, id: &str, expected_fingerprint: u64) -> bool {
        self.records
            .get(id)
            .is_some_and(|record| record.fingerprint == expected_fingerprint)
    }

    pub fn tags(&self, id: &str, expected_fingerprint: u64) -> Option<(&str, &[String])> {
        let record = self.records.get(id)?;
        if record.fingerprint != expected_fingerprint {
            return None;
        }
        Some((&record.main_tag, &record.subtags))
    }

    pub fn similarities(
        &self,
        id: &str,
        expected_fingerprint: u64,
        query: &[f32],
    ) -> Option<SemanticSimilarities> {
        if query.len() != self.dimensions {
            return None;
        }
        let record = self.records.get(id)?;
        if record.fingerprint != expected_fingerprint {
            return None;
        }
        let content = record
            .content_vectors
            .iter()
            .map(|vector| vector.similarity(query))
            .reduce(f32::max)
            .map(|score| score.clamp(-1.0, 1.0))?;
        Some(SemanticSimilarities {
            content,
            taxonomy: record.taxonomy_vector.similarity(query).clamp(-1.0, 1.0),
        })
    }
}

struct IndexReader<'a> {
    bytes: &'a [u8],
    offset: usize,
}

impl<'a> IndexReader<'a> {
    fn new(bytes: &'a [u8]) -> Self {
        Self { bytes, offset: 0 }
    }

    fn take(&mut self, length: usize) -> Result<&'a [u8], String> {
        let end = self
            .offset
            .checked_add(length)
            .filter(|end| *end <= self.bytes.len())
            .ok_or_else(|| "Semantic index is truncated".to_string())?;
        let value = &self.bytes[self.offset..end];
        self.offset = end;
        Ok(value)
    }

    fn read_u16(&mut self) -> Result<u16, String> {
        Ok(u16::from_le_bytes(
            self.take(2)?.try_into().expect("two-byte slice"),
        ))
    }

    fn read_u32(&mut self) -> Result<u32, String> {
        Ok(u32::from_le_bytes(
            self.take(4)?.try_into().expect("four-byte slice"),
        ))
    }

    fn read_u64(&mut self) -> Result<u64, String> {
        Ok(u64::from_le_bytes(
            self.take(8)?.try_into().expect("eight-byte slice"),
        ))
    }

    fn read_f32(&mut self) -> Result<f32, String> {
        Ok(f32::from_le_bytes(
            self.take(4)?.try_into().expect("four-byte slice"),
        ))
    }

    fn is_finished(&self) -> bool {
        self.offset == self.bytes.len()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn semantic_index_round_trip_preserves_similarity() {
        let embedding = vec![1.0 / (EMBEDDING_DIMENSIONS as f32).sqrt(); EMBEDDING_DIMENSIONS];
        let record = SemanticRecord {
            id: "q-1".to_string(),
            fingerprint: 42,
            main_tag: "Geography".to_string(),
            subtags: vec![
                "Rivers, Lakes & Water Resources".to_string(),
                "Indian Geography".to_string(),
            ],
            content_vectors: vec![QuantizedVector::from_embedding(&embedding).unwrap()],
            taxonomy_vector: QuantizedVector::from_embedding(&embedding).unwrap(),
        };
        let encoded = SemanticIndex::from_records(vec![record])
            .to_bytes()
            .unwrap();
        let decoded = SemanticIndex::from_bytes(&encoded).unwrap();
        let scores = decoded.similarities("q-1", 42, &embedding).unwrap();
        assert!(scores.content > 0.999);
        assert!(scores.taxonomy > 0.999);
        assert!(decoded.similarities("q-1", 41, &embedding).is_none());
        assert_eq!(
            decoded.tags("q-1", 42),
            Some((
                "Geography",
                &[
                    "Rivers, Lakes & Water Resources".to_string(),
                    "Indian Geography".to_string()
                ][..]
            ))
        );
    }

    #[test]
    fn content_and_taxonomy_similarity_are_independent() {
        let mut content = vec![0.0; EMBEDDING_DIMENSIONS];
        content[0] = 1.0;
        let mut taxonomy = vec![0.0; EMBEDDING_DIMENSIONS];
        taxonomy[1] = 1.0;
        let record = SemanticRecord {
            id: "q-1".to_string(),
            fingerprint: 42,
            main_tag: "Geography".to_string(),
            subtags: vec!["Rivers, Lakes & Water Resources".to_string()],
            content_vectors: vec![QuantizedVector::from_embedding(&content).unwrap()],
            taxonomy_vector: QuantizedVector::from_embedding(&taxonomy).unwrap(),
        };
        let index = SemanticIndex::from_records(vec![record]);
        let scores = index.similarities("q-1", 42, &taxonomy).unwrap();
        assert!(scores.content.abs() < f32::EPSILON);
        assert!(scores.taxonomy > 0.999);
    }

    #[test]
    fn canonical_text_and_fingerprint_change_with_options() {
        let first = canonical_question_text("Water?", &[("a", "River")]);
        let second = canonical_question_text("Water?", &[("a", "Ocean")]);
        assert_ne!(fingerprint(&first), fingerprint(&second));
    }
}
